# Generated by Django 4.0.3 on 2022-03-09 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_coupon_codes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coupon_codes',
            options={'verbose_name': 'Coupon Code', 'verbose_name_plural': 'Coupon Codes'},
        ),
        migrations.AlterModelOptions(
            name='user_credit',
            options={'verbose_name': 'User Credit', 'verbose_name_plural': 'User Credits'},
        ),
    ]
