# Generated by Django 4.0.3 on 2022-03-15 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_user_join_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='alert_status',
            field=models.BooleanField(default=True),
        ),
    ]
