# Generated by Django 4.0.3 on 2022-03-09 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campaign_leads',
            options={'verbose_name': 'Campaign Lead', 'verbose_name_plural': 'Campaign Leads'},
        ),
        migrations.AlterModelOptions(
            name='campaigns',
            options={'verbose_name': 'Campaign', 'verbose_name_plural': 'Campaigns'},
        ),
        migrations.AlterModelOptions(
            name='leads',
            options={'verbose_name': 'Lead', 'verbose_name_plural': 'Leads'},
        ),
    ]
