# Generated by Django 4.0.3 on 2022-03-09 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_alter_campaign_leads_options_alter_campaigns_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leads',
            name='linkedin_profile',
            field=models.URLField(blank=True, max_length=100, null=True),
        ),
    ]
