# Generated by Django 4.0.3 on 2022-03-11 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_alter_leads_linkedin_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leads',
            name='linkedin_profile',
            field=models.URLField(blank=True, max_length=400, null=True),
        ),
    ]
