# Generated by Django 4.0.3 on 2022-03-13 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0004_alter_leads_linkedin_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaigns',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
