# Generated by Django 4.0.3 on 2022-03-13 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0005_campaigns_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaigns',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
