# Generated by Django 4.0.3 on 2022-03-28 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0006_alter_campaigns_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='leads',
            name='employee_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='leads',
            name='industry',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='leads',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
