# Generated by Django 4.0.3 on 2022-03-29 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0008_alter_campaigns_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leads',
            name='employee_total',
            field=models.CharField(blank=True, default=0, max_length=100, null=True),
        ),
    ]
