# Generated by Django 4.0.3 on 2022-03-11 15:27

import dashboard.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file_uploader',
            name='file',
            field=models.FileField(upload_to='uploads/', validators=[dashboard.models.validate_file_extension]),
        ),
    ]
