# Generated by Django 4.0.3 on 2022-03-19 11:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_alter_packages_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription_data',
            name='expire_date',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 4, 18, 17, 24, 47, 560441), null=True),
        ),
    ]
