# Generated by Django 4.0.3 on 2022-03-24 07:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0005_alter_subscription_data_expire_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription_data',
            name='expire_date',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 4, 23, 13, 12, 3, 639312), null=True),
        ),
    ]
