# Generated by Django 4.0.3 on 2022-04-01 11:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0012_alter_subscription_data_expire_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription_data',
            name='expire_date',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 5, 1, 17, 38, 53, 219887), null=True),
        ),
    ]
